
// import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header/Header";
import { SkeletonTheme } from "react-loading-skeleton";
import 'react-loading-skeleton/dist/skeleton.css'
import { Toaster } from "react-hot-toast";

//generate static metadata
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {

  //generatestaticdataprops
  return (
    <html lang="en">
      <body
        className={`
          
          min-h-screen flex flex-col`}
      >
        <SkeletonTheme baseColor="#BBBBBB" highlightColor="#CCCCCC">
          <Toaster position="bottom-left" />

          <Header />
          <div className="flex-1 mx-5">
            {children}
          </div>
        </SkeletonTheme>
      </body>
    </html>
  );
}
